config/routes.rb
Flashcards::Application.routes.draw do
  root to: "homes#show"
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :decks do        #, only: [:index, :show]
    resources :cards, except: [:index]
  end
end

  # get "/decks" => "decks#index"
  # get "/decks/new" => "decks#new"
  # post "/decks" => "decks#create"
  # get "/decks/:id" => "decks#show", as: :deck 
  # get "/decks/:id/edit" => "decks#edit"
  # put "/decks/:id" => "decks#update"
  # delete "/decks/:id" => "decks#destroy"

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :back, :front
  belongs_to :deck # belongs_to is adding methods - here a method called deck - sql returns and then addes
end

app/models/deck.rb
class Deck < ActiveRecord::Base
	attr_accessible :name
	has_many :cards
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username
  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
  	if cookies[:user_id] # don't need to encrypt here
  		User.find_by_id(cookies.signed[:user_id]) #here we need to decrypt
  	end
  end
  helper_method :current_user

  def signed_in? #all the question mark is tells you and fellow developers 
  	#that you are expecting truthy or falsy, an ! represents destructive
  	current_user
  end
  helper_method :signed_in?

  def require_login
  	unless signed_in?    #unless is essentialy if not
  		redirect_to new_session_path
  	end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
	before_filter :require_login
	
	def show
		@card = find_card
	end

	def new
		@card = deck.cards.new
	end

	def create
		@card = deck.cards.new(card_params)
		@card.save
		redirect_to deck
	end
	
	def edit
		@card = find_card
	end

	def update
		@card = find_card
		@card.update_attributes(card_params)
		redirect_to deck
	end

	def destroy
		find_card.destroy
		redirect_to deck
	end

private
def deck
		@_deck ||= current_user.decks.find(params[:deck_id]) #memozitation #underscore - instance variable that shouldn't be touched
	end

def find_card
	deck.cards.find(params[:id])
end

def card_params
	params[:card]
end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
	before_filter :require_login

	def index
		@decks = current_user.decks
	end

	def new
		@deck = decks.new
	end

	def create
		@deck = decks.new(params[:deck])
		@deck.save
		redirect_to decks_path
	end

	def show
		@deck = decks.find(params[:id])
	end

	def edit
		@deck = decks.find(params[:id])
	end

	def update 
		@deck = decks.find(params[:id])
		@deck.update_attributes(params[:deck])
		redirect_to @deck
	end

	def destroy
		@deck = decks.find(params[:id])
		@deck.destroy
		redirect_to decks_path
	end

private

def decks
	current_user.decks
end


end 

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def show
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by_username(params[:session][:username])
		cookies.signed[:user_id] = user.id #signed - encrypts & decrypts
		redirect_to decks_path
	end

	def destroy
		cookies.delete(:user_id)
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	@user.save
  	redirect_to decks_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/edit.html.erb
<%= form_for([@card.deck, @card]) do |form| %>

<div>
	<%= form.label :front %>
	<%= form.text_field :front %>
</div>

<div>
	<%= form.label :back %>
	<%= form.text_field :back %>
</div>

<div>
	<%= form.submit "Edit card" %>
</div>

<% end %>

app/views/cards/index.html.erb
<%= link_to "New cards", new_card_path %>
<% @cards.each do |card| %>
	<div>
		<%= link_to card.front, card %>
		<%= link_to card.back, card %>
	</div>
<% end %>

app/views/cards/new.html.erb
<%= form_for([@card.deck, @card]) do |form| %>

<div>
	<%= form.label :front %>
	<%= form.text_field :front %>
</div>

<div>
	<%= form.label :back %>
	<%= form.text_field :back %>
</div>

<div>
	<%= form.submit "New card" %>
</div>

<% end %>

app/views/cards/show.html.erb
<div><%= @card.front %> </div>
<div><%= @card.back %> </div>

app/views/decks/edit.html.erb
<%= form_for(@deck) do |form| %>
	<div>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</div>
	<%= form.submit "Update deck" %>
<% end %>

app/views/decks/index.html.erb
<%= link_to "New deck", new_deck_path %>
<% @decks.each do |deck| %>
	<div>
		<%= link_to deck.name, deck %>
		<%=  link_to "Edit", edit_deck_path(deck) %>
		<%=  link_to "Destroy", deck, method: :delete, confirm: "Are you sure?" %>
	</div>
<% end %>

app/views/decks/new.html.erb
<%= form_for(@deck) do |form| %>
<div>
	<%= form.label :name %>
	<%= form.text_field :name %>
</div>
<%= form.submit "New deck" %>
<% end %>

app/views/decks/show.html.erb
<%= @deck.name %>

<%= link_to "New cards", new_deck_card_path(@deck) %>

<% @deck.cards.each do |card| %>
	<div>
		<%= link_to card.front, [@deck, card] %>
		<%= link_to "Edit", edit_deck_card_path(@deck, card) %>
		<%= link_to "Destroy", [@deck, card], method: :delete, confirm: "Are you sure?" %>
	</div>
<% end %>

app/views/homes/show.html.erb
<%= link_to "Sign in", new_session_path %>
<%= link_to "Sign up", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<% if signed_in? %>
	Welcome <%= current_user.username %>
	<%= link_to "Sign out", session_path, method: :delete %>
	<% else %>
	<%= link_to "Sign in" , new_session_path %>
	<%= link_to "Sign Up", new_user_path %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
<div>
	<%= form.label :username %>
	<%= form.text_field :username %>
</div>
<%= form.submit "Sign Up" %>
<% end %>